version: '3.3'
services:
  fsm-executor:
    image: seedsregistry.azurecr.io/fsm-executor-seeds:latest
    ports:
      - ${FSM_EXEC_PORT}:${FSM_EXEC_PORT}
    environment:
      AZURE_SERVICE_BUS_CONNECTION_STRING: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
      AZURE_SERVICE_BUS_PRICING_TIER: ${AZURE_SERVICE_BUS_PRICING_TIER}
      AZURE_SERVICE_BUS_CLIENT_ID: ${AZURE_SERVICE_BUS_CLIENT_ID}
      FSM_SUBS_NAME: ${FSM_SUBS_NAME}
      PLACE_URL: ${PLACE_URL}
      PLACE_GET_LATEST_VERSION_API: ${PLACE_GET_LATEST_VERSION_API}
      PLACE_GET_FSM_API: ${PLACE_GET_FSM_API}
      PLACE_GET_FSM_BY_ID_API: ${PLACE_GET_FSM_BY_ID_API}
      IVR_CONTAINER_NAME: ${IVR_CONTAINER_NAME}
      IVR_PORT: ${IVR_PORT}
      FSM_EXEC_CONTAINER_NAME: ${FSM_EXEC_CONTAINER_NAME}
      FSM_EXEC_PORT: ${FSM_EXEC_PORT}
    networks:
      - app-net
  ivr:
    depends_on:
      - fsm-executor
    image: ivr-server-vm:2.6
    ports:
      - ${IVR_PORT}:${IVR_PORT}
    environment:
      VONAGE_NUMBER: ${VONAGE_NUMBER}
      VONAGE_API_KEY: ${VONAGE_API_KEY}
      VONAGE_API_SECRET: ${VONAGE_API_SECRET}
      VONAGE_APPLICATION_ID: ${VONAGE_APPLICATION_ID}
      PUBSUB_CONNECTION_STRING: ${PUBSUB_CONNECTION_STRING}
      BLOB_STORAGE_CONNECTION_STRING: ${BLOB_STORAGE_CONNECTION_STRING}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      AZURE_PUBSUB_HUB_NAME: ${AZURE_PUBSUB_HUB_NAME}
      PRIVATE_KEY_NAME: ${PRIVATE_KEY_NAME}
      CONFERENCE_COLLECTION_NAME: ${CONFERENCE_COLLECTION_NAME}
      CONFERENCE_LOG_COLLECTION_NAME: ${CONFERENCE_LOG_COLLECTION_NAME}
      MONO_CALL_USER_COLLECTION_NAME: ${MONO_CALL_USER_COLLECTION_NAME}
      MONOCALL_LOG_COLLECTION_NAME: ${MONOCALL_LOG_COLLECTION_NAME}
      USER_SPENT_TIME_FOR_PULLMODEL_COLLECTION: ${USER_SPENT_TIME_FOR_PULLMODEL_COLLECTION}
      PULL_MODEL_INSIGHTS_COLLECTION: ${PULL_MODEL_INSIGHTS_COLLECTION}
      UNHANDLED_EXCEPTION_COLLECTION: ${UNHANDLED_EXCEPTION_COLLECTION}
      WARNING_COLLECTION: ${WARNING_COLLECTION}
      SEEDS_SERVER_BASE_URL: ${SEEDS_SERVER_BASE_URL}
      SEEDS_IVR_SERVER_BASE_URL: ${SEEDS_IVR_SERVER_BASE_URL}
      IVR_SERVER_HOST_NAME: ${IVR_SERVER_HOST_NAME}
      IVR_CONTAINER_NAME: ${IVR_CONTAINER_NAME}
      IVR_PORT: ${IVR_PORT}
      FSM_EXEC_CONTAINER_NAME: ${FSM_EXEC_CONTAINER_NAME}
      FSM_EXEC_PORT: ${FSM_EXEC_PORT}
    networks:
      - app-net
networks:
  app-net:
    driver: bridge